code:
  204: "No Content"
  206: "Partial Content"
  301: "永久重定向"
  303: "See Other"
  304: "Not Modified"
  307: "Temporary Redirect"
  400: "Bad Request"
  401: "Unauthorized"
  403: "Forbidden"
  404: "Not Found"
  409: "Conflict"
  500: "Internal Server Error"
  503: "Service Unavailable"
